version: '3'

services:
  redis:
    image: redis:3.0-alpine
    ports:
      - '6379:6379'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'magalu'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'