version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'magalu'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
  zip-code-finder:
    image: zip-code-finder:1.0.0
    restart: always
    depends_on: 
       db:
        condition: service_healthy
    environment:
      NODE_ENV: 'local'
      NODE_PORT: '8081'
      JWT_SECRET: 'mysecret'
    ports:
      - '8081:8081'
